#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information() {
    local subdomain="$2"
    local domain="$1"

    result=$(dig "$subdomain.$domain" +short)

    if [ -z "$result" ]; then
        echo "No information found for $subdomain.$domain"
    else
        record_type=$(echo "$result" | awk '{if (/\./) print "CNAME"; else print "A"}')
        destination=$(echo "$result" | awk 'NR==1{print}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        domain_information "$1" "$sub"
    done
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
