#!/usr/bin/env bash
# Function to display subdomain information
# Function to display subdomain information
display_info() {
    local subdomain=$1
    local record_type=$2
    local destination=$3

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the required arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

# Define subdomains and their corresponding IP addresses
subdomains=("www" "lb-01" "web-01" "web-02")

# Loop through subdomains and display information
for sub in "${subdomains[@]}"; do
    dig_output=$(dig +short $sub.$domain)

    if [ -n "$dig_output" ]; then
        destination=$dig_output
        record_type=$(echo "$dig_output" | grep -q '\.' && echo "CNAME" || echo "A")
        display_info $sub $record_type $destination
    else
        echo "No record found for $sub.$domain"
    fi
done

# Display information for the specified subdomain if provided
if [ -n "$subdomain" ]; then
    dig_output=$(dig +short $subdomain.$domain)

    if [ -n "$dig_output" ]; then
        destination=$dig_output
        record_type=$(echo "$dig_output" | grep -q '\.' && echo "CNAME" || echo "A")
        display_info $subdomain $record_type $destination
    else
        echo "No record found for $subdomain.$domain"
    fi
fi
