#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information() {
    local subdomain="$2"
    local domain="$1"

    line=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $1, $4}')

    if [ -z "$line" ]; then
        echo "No information found for $subdomain.$domain"
    else
        echo "$line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    fi
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        domain_information "$1" "$sub"
    done
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
